---
version: "3"
services:
  reverse_proxy:
    image: traefik:v1.7
    domainname: ${DOMAINNAME}
    container_name: traefik
    command: --api --docker
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    networks:
      - default
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/traefik:/etc/traefik

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default
    container_name: mysql
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DOCKERDIR}/mysql:/var/lib/mysql

  wiki:
    image: mediawiki-o365:dev
    container_name: wiki365
    restart: always
    links:
      - db
    depends_on:
      - db
    networks:
      - default
      - traefik_proxy
    ports:
      - "80"
    environment:
      - WIKI_PATH=${WIKI_PATH}
      - WIKI_NAME=${WIKI_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SIMPLESAML_PATH=${SIMPLESAML_PATH}
      - BASE_URL=${BASE_URL}
      - WIKI_EMAIL=${WIKI_EMAIL}
      - MS_ENTITYID=${MS_ENTITYID}
      - MS_IDP=${MS_IDP}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
    - ${DOCKERDIR}/mediawiki-data/images:/var/www/html/wiki/images
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wiki"
      - "traefik.frontend.rule=Host:wiki.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.contentSecurityPolicy=upgrade-insecure-requests"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncluSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
