---
version: "3.7"
services:
  reverse_proxy:
    image: traefik:v2.3
    networks:
      - traefik-swarm
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/log:/etc/traefik/log
    deploy:
      placement:
        constraints: [node.role==manager]
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yml
        mode: 0444
      - source: traefik_rules
        target: /etc/traefik/rules.yml
        mode: 0444

  wiki_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - traefik-swarm
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role==manager]

  db_backup:
    image: mysql-backup:0.10.0
    depends_on:
      - wiki_db
    networks:
      - traefik-swarm
    environment:
      - TZ=${TZ}
      - DB_SERVER=wiki_db
      - DB_USER=root
      - DB_PASS_FILE=/run/secrets/mysql_root_password
      - DB_DUMP_TARGET=${DB_DUMP_TARGET}
      - DB_DUMP_BEGIN=0020
      - DB_DUMP_TARGET=s3://wiki-difuze-db-backup/mysql_backup
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/aws_access_key_id
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/aws_secret_access_key
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - aws_access_key_id
      - aws_secret_access_key


  wiki:
    image: wiki365:1.35a
    depends_on:
      - wiki_db
    networks:
      - traefik-swarm
    environment:
      - WIKI_PATH=${WIKI_PATH}
      - WIKI_NAME=${WIKI_NAME}
      - MYSQL_DB_HOST=wiki_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_root_password
      - SIMPLESAML_PATH=${SIMPLESAML_PATH}
      - BASE_URL=${BASE_URL}
      - WIKI_EMAIL=${WIKI_EMAIL}
      - MS_ENTITYID_FILE=/run/secrets/ms_entityid
      - MS_IDP_FILE=/run/secrets/ms_idp
      - FEDERATION_URL=${FEDERATION_URL}
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - ms_entityid
      - ms_idp
      - wiki_email
    volumes:
    - images:/var/www/html/wiki/images
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wiki.entrypoints=http"
        - "traefik.http.routers.wiki.rule=Host(`wiki.${DOMAINNAME}`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.wiki.middlewares=https-redirect"
        - "traefik.http.routers.wiki-secure.entrypoints=https"
        - "traefik.http.routers.wiki-secure.rule=Host(`wiki.${DOMAINNAME}`)"
        - "traefik.http.routers.wiki-secure.tls=true"
        - "traefik.http.routers.wiki-secure.tls.certresolver=http"
        - "traefik.http.services.wiki.loadbalancer.server.port=80"
      placement:
        constraints: [node.role==manager]

networks:
  traefik-swarm:
    external: true

volumes:
  images:
  mysql:

configs:
  traefik_config:
    file: ./traefik/traefik.yml
  traefik_rules:
    file: ./traefik/rules.yml
  cert_store:
    file: ./traefik/acme.json

secrets:
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  ms_entityid:
    external: true
  ms_idp:
    external: true
  wiki_email:
    external: true
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true
