---
version: "3.7"
services:
  reverse_proxy:
    image: traefik:v1.7
    environment:
      - DO_AUTH_TOKEN_FILE=/run/secrets/do_auth_token
    networks:
      - traefik-swarm
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role==manager]
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
        mode: 0444
      - source: traefik_storage
        target: /etc/traefik/acme/acme.json
        mode: 0600
    secrets:
      - do_auth_token

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - traefik-swarm
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role==manager]

  wiki:
    image: media-wiki-o365:dev
    depends_on:
      - db
    networks:
      - traefik-swarm
    ports:
      - "80"
    environment:
      - WIKI_PATH=${WIKI_PATH}
      - WIKI_NAME=${WIKI_NAME}
      - MYSQL_DB_HOST=wiki_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_root_password
      - SIMPLESAML_PATH=${SIMPLESAML_PATH}
      - BASE_URL=${BASE_URL}
      - WIKI_EMAIL_FILE=/run/secrets/wiki_email
      - MS_ENTITYID_FILE=/run/secrets/ms_entityid
      - MS_IDP_FILE=/run/secrets/ms_idp
      - PUID=${PUID}
      - PGID=${PGID}
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - ms_entityid
      - ms_idp
      - wiki_email
    volumes:
    - images:/var/www/html/wiki/images
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=wiki"
        - "traefik.frontend.rule=Host:wiki.${DOMAINNAME}"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-swarm"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.contentSecurityPolicy=upgrade-insecure-requests"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
        - "traefik.frontend.headers.STSIncluSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
      placement:
        constraints: [node.role==manager]

networks:
  traefik-swarm:
    external: true

volumes:
  images:
  mysql:

configs:
  traefik_toml:
    file: ./traefik/traefik.toml
  traefik_storage:
    file: ./traefik/acme/acme.json

secrets:
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  do_auth_token:
    external: true
  ms_entityid:
    external: true
  ms_idp:
    external: true
  wiki_email:
    external: true
