# Replace DOMAINNAME and EMAIL by your info

logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
#InsecureSkipVerify = true
defaultEntryPoints = ["https", "http"]

[api]
  entryPoint = "traefik"
  dashboard = false

[traefikLog]
filePath = "/etc/traefik/log/traefik.log"
[accessLog]
filePath = "/etc/traefik/log/access.log"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    ]
    [entryPoints.http.forwardedHeaders]

[file]
  watch = true
  directory = "/etc/traefik/rules/"

# Let's encrypt configuration
[acme]
email = "EMAIL" #any email id will work
storage="/etc/traefik/acme/acme.json"
# Comment out when ready to move in production. Use for testing to avoid blocking by Let's Encrypt rate limit
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
acmeLogging=true
onHostRule = true
onDemand = false
[acme.httpChallenge]
  entrypoint = 'http'
[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0
[[acme.domains]]
   main = "DOMAINNAME"
[[acme.domains]]
   main = "*.DOMAINNAME"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "DOMAINNAME"
watch = true
# This will hide all docker containers that don't have explicitly
# set label to "enable"
exposedbydefault = false
